# Generated by Django 2.2.7 on 2019-12-06 14:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='comment_thread',
        ),
        migrations.RemoveField(
            model_name='course',
            name='comment_thread',
        ),
        migrations.RemoveField(
            model_name='resourcepart',
            name='comment_thread',
        ),
        migrations.AddField(
            model_name='comment',
            name='courses',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='app.Course'),
        ),
        migrations.AddField(
            model_name='comment',
            name='resource_parts',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='app.ResourcePart'),
        ),
        migrations.AddField(
            model_name='comment',
            name='resources',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='app.Resource'),
        ),
        migrations.DeleteModel(
            name='CommentThread',
        ),
    ]
