# Generated by Django 2.2.7 on 2020-01-04 20:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resource',
            name='file',
        ),
        migrations.AlterField(
            model_name='resourcepart',
            name='resource_part_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='app.ResourcePartType'),
        ),
    ]
