# Generated by Django 2.2.7 on 2019-11-16 17:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursecommentthread',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_comment_threads', to='app.Course'),
        ),
        migrations.AlterField(
            model_name='resourcecommentthread',
            name='resource',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resource_comment_threads', to='app.Resource'),
        ),
    ]
