# Generated by Django 2.2.7 on 2020-01-04 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20200104_2053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='date',
            field=models.DateField(null=True),
        ),
    ]
