# Generated by Django 2.2.7 on 2019-12-06 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20191206_1431'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='courses',
            new_name='course',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='resources',
            new_name='resource',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='resource_parts',
            new_name='resource_part',
        ),
    ]
