version: "3.7"

services:
  db-ci:
    container_name: db-ci
    image: postgres:12.4-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=skole
      - POSTGRES_USER=username
      - POSTGRES_PASSWORD=password
    logging:
      driver: none

  backend-ci:
    container_name: backend-ci
    build:
      context: ..
      dockerfile: Dockerfile
      target: ci
      args:
        install_dev_dependencies: 1
    environment:
      - DEBUG=1
      - SECRET_KEY=skole
      - DATABASE_URL=postgres://username:password@db-ci:5432/skole
    depends_on:
      - db-ci
