version: "3.7"

services:
  db:
    container_name: db
    image: postgres:12.2-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=skole
      - POSTGRES_USER=username
      - POSTGRES_PASSWORD=password
    logging:
      driver: none

  backend:
    container_name: backend
    build:
      context: .
      dockerfile: Dockerfile
      target: circleci
    environment:
      - DEBUG=1
      - SECRET_KEY=skole
      - DATABASE_URL=postgres://username:password@db:5432/skole
    depends_on:
      - db
