FROM python:3.8.2-alpine3.11

RUN adduser --disabled-password user
WORKDIR /home/user/app
RUN chown user:user /home/user/app

ENV PATH="/home/user/.local/bin:${PATH}"
ENV PYTHONUNBUFFERED=1
ENV PYTHONOPTIMIZE=1

RUN apk add --update-cache --no-cache postgresql-client gettext jpeg-dev libmagic

COPY --chown=user:user requirements.txt .

RUN apk add --update-cache --no-cache --virtual .tmp-build-deps \
        gcc libc-dev linux-headers postgresql-dev musl-dev zlib zlib-dev \
    && su user -c 'pip install --user --no-cache-dir --upgrade pip' \
    && su user -c 'pip install --user --no-cache-dir -r requirements.txt' \
    && apk del .tmp-build-deps

USER user

COPY --chown=user:user . .
