version: '3'

services:
  backend:
    container_name: backend
    build: .
    env_file:
      - ./.env.circleci
    volumes:
      - ./:/app/
      - ./htmlcov:/app/htmlcov
    depends_on:
      - db
  db:
    container_name: db
    image: postgres:12.0-alpine
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env.circleci

volumes:
  postgres_data:
