FROM python:3.8.5-alpine3.12

RUN adduser --disabled-password user
WORKDIR /home/user/app
RUN chown user:user /home/user/app

ENV PATH="/home/user/.local/bin:${PATH}"
ENV PYTHONUNBUFFERED=1
ENV PYTHONOPTIMIZE=1

COPY --chown=user:user requirements.txt .

RUN apk update \
    && apk add postgresql-client gettext jpeg-dev libmagic \
    && apk add --virtual=/tmp/build_deps gcc libc-dev linux-headers postgresql-dev musl-dev zlib zlib-dev \
    && su user -c 'pip install --user --no-cache-dir --upgrade --disable-pip-version-check pip' \
    && su user -c 'pip install --user --no-cache-dir -r requirements.txt' \
    && apk del /tmp/build_deps && rm -rf /var/cache/apk/*

USER user

COPY --chown=user:user . .

CMD python manage.py migrate \
    && python manage.py collectstatic --noinput \
    && python manage.py compilemessages \
    && gunicorn --log-level info --access-logfile '-' --workers 3 --bind 0.0.0.0:8000 config.wsgi
