version: '3'

services:
  backend:
    container_name: backend
    build: .
    ports:
      - '8000:8000'
    env_file:
      - ./.env.circleci
    volumes:
      - ./src:/app/src
      - ./htmlcov:/app/htmlcov
    command: >
      sh -c "python src/manage.py wait_for_db &&
             python src/manage.py migrate &&
             python src/manage.py runserver 0.0.0.0:8000"
    depends_on:
      - db
  db:
    container_name: db
    image: postgres:12.0-alpine
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env.circleci

volumes:
  postgres_data:
