[tool.black]
exclude = "migrations/.*"

[tool.coverage.run]
branch = true
omit = [
  "*/migrations/*",
  "*/tests/*",
]

[tool.isort]
include_trailing_comma = true
line_length = 88
multi_line_output = 3
skip_glob = "*/migrations/*"

[tool.pytest.ini_options]
DJANGO_SETTINGS_MODULE = "config.settings"
addopts = "--nomigrations --doctest-modules"
