# Generated by Django 2.2.7 on 2020-03-05 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='attachment',
            field=models.FileField(blank=True, upload_to='uploads/attachments'),
        ),
    ]
