# Generated by Django 2.2.7 on 2020-03-15 13:59

import core.utils.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20200315_1213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='attachment',
            field=models.FileField(blank=True, upload_to='uploads/attachments', validators=[core.utils.validators.ValidateFileSizeAndType(3, ['image/jpeg', 'image/png'])]),
        ),
        migrations.AlterField(
            model_name='resource',
            name='file',
            field=models.FileField(blank=True, max_length=500, upload_to='uploads/resources', validators=[core.utils.validators.ValidateFileSizeAndType(5, ['application/pdf'])]),
        ),
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, upload_to='uploads/avatars', validators=[core.utils.validators.ValidateFileSizeAndType(2, ['image/jpeg', 'image/png'])]),
        ),
    ]
