# Generated by Django 2.2.7 on 2020-03-21 14:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20200315_1359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='betacode',
            name='usages',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
