# Generated by Django 2.2.7 on 2020-04-07 19:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_migrate_translatable_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='city',
            name='name',
        ),
        migrations.RemoveField(
            model_name='country',
            name='name',
        ),
        migrations.RemoveField(
            model_name='resourcetype',
            name='name',
        ),
        migrations.RemoveField(
            model_name='school',
            name='name',
        ),
        migrations.RemoveField(
            model_name='schooltype',
            name='name',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='name',
        ),
    ]
