# Generated by Django 2.2.7 on 2020-04-07 19:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_untranslated_fields'),
    ]

    operations = [
        migrations.RenameField(
            model_name='citytranslation',
            old_name='name_t',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='countrytranslation',
            old_name='name_t',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='resourcetypetranslation',
            old_name='name_t',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='schooltranslation',
            old_name='name_t',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='schooltypetranslation',
            old_name='name_t',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='subjecttranslation',
            old_name='name_t',
            new_name='name',
        ),
    ]
