from .messages import (
    AUTHENTICATION_FAILED_MESSAGE,
    LANGUAGE_SET_SUCCESSFULLY_MESSAGE,
    NOT_ANONYMOUS_MESSAGE,
    NOT_ADMIN_MESSAGE,
    NOT_OWNER_MESSAGE,
    OLD_PASSWORD_NOT_CORRECT_MESSAGE,
    PASSWORD_SET_SUCCESSFULLY_MESSAGE,
    PASSWORDS_DO_NOT_MATCH_MESSAGE,
    READ_ONLY_MESSAGE,
    UNABLE_TO_AUTHENTICATE_MESSAGE,
    USER_DOES_NOT_EXIST_MESSAGE,
    USER_REGISTERED_SUCCESSFULLY_MESSAGE,
)
