from .school_types import SCHOOL_TYPES, UNIVERSITY, UNIVERSITY_OF_APPLIED_SCIENCES, HIGH_SCHOOL
from .resource_types import RESOURCE_TYPES, EXAM, NOTE, EXERCISE, OTHER
from .languages import LANGUAGES, ENGLISH, FINNISH, SWEDISH
