UNIVERSITY = "UNIVERSITY"
UNIVERSITY_OF_APPLIED_SCIENCES = "UNIVERSITY_OF_APPLIED_SCIENCES"
HIGH_SCHOOL = "HIGH_SCHOOL"


SCHOOL_TYPES = (
    (UNIVERSITY, "university"),
    (UNIVERSITY_OF_APPLIED_SCIENCES, "university of applied sciences"),
    (UNIVERSITY, "high school"),
)
