version: 2

jobs:
  build:
    branches:
      ignore:
        - develop
    machine:
      image: ubuntu-1604:201903-01
    steps:
      - checkout
      - run:
          name: "Run linter, type-check, and tests"
          command: >
            docker-compose -f docker-compose-circleci.yml up --abort-on-container-exit
            && docker cp backend:/home/user/app/htmlcov .
      - store_artifacts:
          path: htmlcov
