version: 2
jobs:
  build:
    docker:
      - image: circleci/ruby:2.4.1
    steps:
      - checkout
      - setup_remote_docker
      - run: >
          docker-compose -f docker-compose.circleci.yml run --rm backend
              sh -c "pwd && mypy src &&
                     pytest --cov-report html --cov=src src/tests/"
