version: 2

jobs:
  build:
    machine:
      image: ubuntu-1604:201903-01 
    steps:
      - checkout
      - run: docker-compose -f docker-compose.circleci.yml run --rm backend sh -c "mypy src && pytest --cov-report html --cov=src src/tests/"
