version: 2.1

orbs:
  codecov: codecov/codecov@1.1.3

jobs:
  build:
    docker:
      - image: cimg/base:2020.01
    resource_class: small
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: "Check commits of the PR branch"
          command: ./.circleci/check_commits.sh
      - run:
          name: "Run linters, type-check, and tests"
          command: >
            docker-compose --file .circleci/docker-compose-circleci.yml up --build --abort-on-container-exit
            && docker cp backend-circleci:/home/user/app/coverage.xml .
      - codecov/upload:
          file: coverage.xml
