version: 2

jobs:
  build:
    branches:
      ignore:
        - develop
    machine:
      image: ubuntu-1604:201903-01
      docker_layer_caching: true
    steps:
      - checkout
      - run:
          name: "Run linters, type-check, and tests"
          command: >
            docker-compose --file docker-compose-circleci.yml up --build --abort-on-container-exit
            && docker cp backend-circleci:/home/user/app/htmlcov .
      - store_artifacts:
          path: htmlcov
