 version: 2
 jobs:
   build:
     docker:
       - image: circleci/ruby:2.4.1
     steps:
       - checkout
       - run: docker-compose run --rm backend sh -c "mypy src pytest --cov-report html --cov=src src/tests/"
