version: 2.1

orbs:
  codecov: codecov/codecov@1.1.1

jobs:
  build:
    machine:
      image: ubuntu-1604:201903-01
      docker_layer_caching: true
    steps:
      - checkout
      - run:
          name: "Check commits of the PR branch"
          command: ./.circleci/check_commits.sh
      - run:
          name: "Run linters, type-check, and tests"
          command: >
            docker-compose --file .circleci/docker-compose-circleci.yml up --build --abort-on-container-exit
            && docker cp backend-circleci:/home/user/app/coverage.xml .
      - codecov/upload:
          file: coverage.xml
