# Generated by Django 3.1.3 on 2020-12-14 17:51

from __future__ import annotations

import re

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("skole", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(
                error_messages={"unique": "This email is taken."},
                max_length=254,
                unique=True,
                verbose_name="email",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="username",
            field=models.CharField(
                error_messages={"unique": "This username is taken."},
                max_length=30,
                unique=True,
                validators=[
                    django.core.validators.RegexValidator(
                        re.compile("^[A-Za-z0-9ÅÄÖåäö_]+$"),
                        "Usernames can only contain letters, numbers, and underscores.",
                    )
                ],
                verbose_name="username",
            ),
        ),
    ]
