# Generated by Django 3.1.3 on 2020-12-04 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('skole', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='badge',
            old_name='user',
            new_name='users',
        ),
    ]
