# Generated by Django 3.1.4 on 2020-12-06 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skole', '0002_rename_badge_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='last_my_data_query',
            field=models.DateTimeField(help_text='The time when the user last used the GDPR `myData` query.', null=True),
        ),
    ]
