# Generated by Django 3.1.4 on 2021-01-19 19:19

from __future__ import annotations

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("skole", "0002_add_verbose_names"),
    ]

    operations = [
        migrations.CreateModel(
            name="Author",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="resource",
            name="author",
            field=models.ForeignKey(
                blank=True,
                help_text="The author (=copyright owner) of the resource.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="authored_resources",
                to="skole.author",
            ),
        ),
    ]
