# Generated by Django 3.0.6 on 2020-05-04 19:31

from django.db import migrations, models
import skole.utils.validators


class Migration(migrations.Migration):

    dependencies = [
        ('skole', '0003_badge'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, default=None, upload_to='uploads/avatars', validators=[skole.utils.validators.ValidateFileSizeAndType(2, ['image/jpeg', 'image/png'])]),
        ),
    ]
