# Generated by Django 3.1.4 on 2020-12-10 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('skole', '0003_add_user_last_my_data_query'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='activitytype',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='badge',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='city',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='country',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='course',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='resource',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='resourcetype',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='school',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='schooltype',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='star',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='user',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='vote',
            name='deleted_at',
        ),
    ]
