# Generated by Django 3.1.5 on 2021-02-04 11:32

from __future__ import annotations

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("skole", "0003_add_resource_author"),
    ]

    operations = [
        migrations.AddField(
            model_name="comment",
            name="school",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="comments",
                to="skole.school",
            ),
        ),
    ]
