# Generated by Django 3.1.4 on 2020-12-12 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skole', '0004_remove_soft_deletion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='last_my_data_query',
            field=models.DateTimeField(blank=True, help_text='The time when the user last used the GDPR `myData` query.', null=True),
        ),
    ]
