# Generated by Django 3.1.5 on 2021-02-08 22:26
# Manually edited to add the `forwards_func`.
import autoslug.fields
from django.apps.registry import Apps
from django.db import migrations
from django.db.backends.base.schema import BaseDatabaseSchemaEditor


def forwards_func(apps: Apps, schema_editor: BaseDatabaseSchemaEditor) -> None:
    for model_name in (
        "City",
        "Country",
        "Course",
        "Resource",
        "ResourceType",
        "School",
        "SchoolType",
        "Subject",
        "User",
    ):
        model = apps.get_model("skole", model_name)
        for instance in model.objects.all():
            instance.save(update_fields=["slug"])


class Migration(migrations.Migration):

    dependencies = [
        ('skole', '0004_add_school_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='slug',
            field=autoslug.fields.AutoSlugField(always_update=True, default=None, editable=False, null=True, populate_from='__str__', unique=True),
        ),
        migrations.AddField(
            model_name='country',
            name='slug',
            field=autoslug.fields.AutoSlugField(always_update=True, default=None, editable=False, null=True, populate_from='__str__', unique=True),
        ),
        migrations.AddField(
            model_name='course',
            name='slug',
            field=autoslug.fields.AutoSlugField(always_update=True, default=None, editable=False, null=True, populate_from='__str__', unique_with=('name', 'code')),
        ),
        migrations.AddField(
            model_name='resource',
            name='slug',
            field=autoslug.fields.AutoSlugField(always_update=True, default=None, editable=False, null=True, populate_from='__str__', unique_with=('title', 'date')),
        ),
        migrations.AddField(
            model_name='resourcetype',
            name='slug',
            field=autoslug.fields.AutoSlugField(always_update=True, default=None, editable=False, null=True, populate_from='__str__', unique=True),
        ),
        migrations.AddField(
            model_name='school',
            name='slug',
            field=autoslug.fields.AutoSlugField(always_update=True, default=None, editable=False, null=True, populate_from='__str__', unique=True),
        ),
        migrations.AddField(
            model_name='schooltype',
            name='slug',
            field=autoslug.fields.AutoSlugField(always_update=True, default=None, editable=False, null=True, populate_from='__str__', unique=True),
        ),
        migrations.AddField(
            model_name='subject',
            name='slug',
            field=autoslug.fields.AutoSlugField(always_update=True, default=None, editable=False, null=True, populate_from='__str__', unique=True),
        ),
        migrations.AddField(
            model_name='user',
            name='slug',
            field=autoslug.fields.AutoSlugField(always_update=True, default=None, editable=False, null=True, populate_from='username'),
        ),
        migrations.RunPython(code=forwards_func, reverse_code=migrations.RunPython.noop),
    ]
