# Generated by Django 3.1.5 on 2021-02-08 22:26
from __future__ import annotations

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("skole", "0004_add_school_comments"),
    ]

    operations = [
        migrations.AddField(
            model_name="city",
            name="slug",
            field=autoslug.fields.AutoSlugField(
                always_update=True,
                default=None,
                editable=False,
                null=True,
                populate_from="__str__",
                unique=True,
            ),
        ),
        migrations.AddField(
            model_name="country",
            name="slug",
            field=autoslug.fields.AutoSlugField(
                always_update=True,
                default=None,
                editable=False,
                null=True,
                populate_from="__str__",
                unique=True,
            ),
        ),
        migrations.AddField(
            model_name="course",
            name="slug",
            field=autoslug.fields.AutoSlugField(
                always_update=True,
                default=None,
                editable=False,
                null=True,
                populate_from="__str__",
                unique_with=("name", "code"),
            ),
        ),
        migrations.AddField(
            model_name="resource",
            name="slug",
            field=autoslug.fields.AutoSlugField(
                always_update=True,
                default=None,
                editable=False,
                null=True,
                populate_from="__str__",
                unique_with=("title", "date"),
            ),
        ),
        migrations.AddField(
            model_name="resourcetype",
            name="slug",
            field=autoslug.fields.AutoSlugField(
                always_update=True,
                default=None,
                editable=False,
                null=True,
                populate_from="__str__",
                unique=True,
            ),
        ),
        migrations.AddField(
            model_name="school",
            name="slug",
            field=autoslug.fields.AutoSlugField(
                always_update=True,
                default=None,
                editable=False,
                null=True,
                populate_from="__str__",
                unique=True,
            ),
        ),
        migrations.AddField(
            model_name="schooltype",
            name="slug",
            field=autoslug.fields.AutoSlugField(
                always_update=True,
                default=None,
                editable=False,
                null=True,
                populate_from="__str__",
                unique=True,
            ),
        ),
        migrations.AddField(
            model_name="subject",
            name="slug",
            field=autoslug.fields.AutoSlugField(
                always_update=True,
                default=None,
                editable=False,
                null=True,
                populate_from="__str__",
                unique=True,
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="slug",
            field=autoslug.fields.AutoSlugField(
                always_update=True,
                default=None,
                editable=False,
                null=True,
                populate_from="username",
            ),
        ),
    ]
