# Generated by Django 3.1.5 on 2021-02-08 22:26

from typing import Any

import autoslug.fields
from django.db import migrations

from skole.apps import SkoleAppConfig
from skole.models import (
    City,
    Country,
    Course,
    Resource,
    ResourceType,
    School,
    SchoolType,
    Subject,
    User,
)


def forward_func(apps: SkoleAppConfig, schema_editor: Any) -> None:
    for model in [User, Course, Resource, School, Subject, SchoolType, ResourceType, City, Country]:
        for instance in model.objects.all():
            instance.save()


def backwards_func(apps: SkoleAppConfig, schema_editor: Any) -> None:
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('skole', '0004_add_school_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='slug',
            field=autoslug.fields.AutoSlugField(always_update=True, default=None, editable=False, null=True, populate_from='__str__', unique=True),
        ),
        migrations.AddField(
            model_name='country',
            name='slug',
            field=autoslug.fields.AutoSlugField(always_update=True, default=None, editable=False, null=True, populate_from='__str__', unique=True),
        ),
        migrations.AddField(
            model_name='course',
            name='slug',
            field=autoslug.fields.AutoSlugField(always_update=True, default=None, editable=False, null=True, populate_from='__str__', unique_with=('name', 'code')),
        ),
        migrations.AddField(
            model_name='resource',
            name='slug',
            field=autoslug.fields.AutoSlugField(always_update=True, default=None, editable=False, null=True, populate_from='__str__', unique_with=('title', 'date')),
        ),
        migrations.AddField(
            model_name='resourcetype',
            name='slug',
            field=autoslug.fields.AutoSlugField(always_update=True, default=None, editable=False, null=True, populate_from='__str__', unique=True),
        ),
        migrations.AddField(
            model_name='school',
            name='slug',
            field=autoslug.fields.AutoSlugField(always_update=True, default=None, editable=False, null=True, populate_from='__str__', unique=True),
        ),
        migrations.AddField(
            model_name='schooltype',
            name='slug',
            field=autoslug.fields.AutoSlugField(always_update=True, default=None, editable=False, null=True, populate_from='__str__', unique=True),
        ),
        migrations.AddField(
            model_name='subject',
            name='slug',
            field=autoslug.fields.AutoSlugField(always_update=True, default=None, editable=False, null=True, populate_from='__str__', unique=True),
        ),
        migrations.AddField(
            model_name='user',
            name='slug',
            field=autoslug.fields.AutoSlugField(always_update=True, default=None, editable=False, null=True, populate_from='username'),
        ),
        migrations.RunPython(code=forward_func, reverse_code=backwards_func),
    ]
