# Generated by Django 3.1.5 on 2021-02-13 11:42
# Manually edited to add the `forwards_func` and `backwards_func`.
from django.apps.registry import Apps
from django.db import migrations
from django.db.backends.base.schema import BaseDatabaseSchemaEditor


def forwards_func(apps: Apps, schema_editor: BaseDatabaseSchemaEditor) -> None:
    Course = apps.get_model("skole", "Course")
    for course in Course.objects.all():
        course.codes = [code.strip() for code in course.code.split(",")]
        course.save(update_fields=["codes"])


def backwards_func(apps: Apps, schema_editor: BaseDatabaseSchemaEditor) -> None:
    Course = apps.get_model("skole", "Course")
    for course in Course.objects.all():
        course.code = ", ".join(course.codes)
        course.save(update_fields=["code"])


class Migration(migrations.Migration):

    dependencies = [
        ('skole', '0006_add_course_codes'),
    ]

    operations = [
        migrations.RunPython(code=forwards_func, reverse_code=backwards_func)
    ]
