# Generated by Django 3.0.8 on 2020-07-26 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skole', '0006_base_models'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='subject',
        ),
        migrations.AddField(
            model_name='course',
            name='subjects',
            field=models.ManyToManyField(blank=True, related_name='courses', to='skole.Subject'),
        ),
    ]
