# Generated by Django 3.0.8 on 2020-08-02 21:52
# Edited manually to take validator arguments from imports.

import django.core.validators
from django.conf import settings
from django.db import migrations, models

from skole.utils.constants import ValidationErrors


class Migration(migrations.Migration):

    dependencies = [
        ('skole', '0007_resource_subject_many2many'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(error_messages={'unique': 'This username is taken.'}, max_length=30, unique=True, validators=[django.core.validators.RegexValidator(settings.USERNAME_REGEX, ValidationErrors.INVALID_USERNAME)]),
        ),
    ]
