# Generated by Django 3.1.5 on 2021-02-13 11:56

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('skole', '0007_copy_course_code_to_codes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='code',
        ),
        migrations.AlterField(
            model_name='course',
            name='slug',
            field=autoslug.fields.AutoSlugField(always_update=True, default=None, editable=False, null=True, populate_from='__str__', unique_with=('name', 'codes')),
        ),
    ]
