# Generated by Django 3.1 on 2020-08-06 15:42

from django.db import migrations, models
import skole.utils.validators


class Migration(migrations.Migration):

    dependencies = [
        ('skole', '0008_username_regex'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='attachment',
            field=models.ImageField(blank=True, upload_to='uploads/attachments', validators=[skole.utils.validators.ValidateFileSizeAndType(3, [('image/jpeg', 'JPEG'), ('image/png', 'PNG')])]),
        ),
        migrations.AlterField(
            model_name='resource',
            name='file',
            field=models.FileField(blank=True, max_length=500, upload_to='uploads/resources', validators=[skole.utils.validators.ValidateFileSizeAndType(5, [('application/pdf', 'PDF')])]),
        ),
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, default=None, upload_to='uploads/avatars', validators=[skole.utils.validators.ValidateFileSizeAndType(2, [('image/jpeg', 'JPEG'), ('image/png', 'PNG')])]),
        ),
    ]
