# Generated by Django 3.1.1 on 2020-09-11 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('skole', '0009_capital_file_formats'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BetaCode',
        ),
    ]
