# Generated by Django 3.1.5 on 2021-02-23 12:22

from __future__ import annotations

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("skole", "0010_populate_slug_fields"),
    ]

    operations = [
        migrations.CreateModel(
            name="EmailSubscription",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        error_messages={
                            "unique": "A subscription with this email already exists."
                        },
                        max_length=254,
                        unique=True,
                        verbose_name="email",
                    ),
                ),
                ("product_updates", models.BooleanField(default=True)),
                ("blog_posts", models.BooleanField(default=True)),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
