# Generated by Django 3.1.2 on 2020-10-18 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('skole', '0010_delete_betacode'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Starred',
            new_name='Star',
        ),
    ]
