# Generated by Django 3.1.5 on 2021-03-02 14:08

from __future__ import annotations

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("skole", "0014_make_course_user_blank"),
    ]

    operations = [
        migrations.AddField(
            model_name="activity",
            name="school",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="skole.school",
            ),
        ),
    ]
