# Generated by Django 3.1.5 on 2021-03-14 13:12
# Manually edited to add the `forwards_func`.
from __future__ import annotations

from typing import TYPE_CHECKING

import django.utils.translation
from django.apps.registry import Apps
from django.conf import settings
from django.db import migrations
from django.db.backends.base.schema import BaseDatabaseSchemaEditor

if TYPE_CHECKING:
    from skole.models import Course


def slugify_course(self: Course) -> str:
    """Replicates `Course.__str__` which cannot be used during migrations."""
    return f"{self.name} ({', '.join(self.codes)})" if self.codes else self.name


def forwards_func(apps: Apps, schema_editor: BaseDatabaseSchemaEditor) -> None:
    django.utils.translation.activate(settings.LANGUAGE_CODE)
    Course = apps.get_model("skole", "Course")

    for course in Course.objects.all():
        course.slug = slugify_course(course)
        course.save(update_fields=["slug"])


class Migration(migrations.Migration):

    dependencies = [
        ("skole", "0018_dont_ever_update_slugs"),
    ]

    operations = [
        migrations.RunPython(
            code=forwards_func, reverse_code=migrations.RunPython.noop
        ),
    ]
