# Generated by Django 3.1.5 on 2021-03-14 16:35

from __future__ import annotations

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("skole", "0019_force_update_course_slugs"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="badge",
            name="users",
        ),
        migrations.AddField(
            model_name="badge",
            name="completion_score",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="badge",
            name="identifier",
            field=models.CharField(default="", max_length=100),
        ),
        migrations.AddField(
            model_name="badge",
            name="steps",
            field=models.IntegerField(
                null=True, validators=[django.core.validators.MinValueValidator(1)]
            ),
        ),
        migrations.AddField(
            model_name="badge",
            name="tier",
            field=models.CharField(
                choices=[
                    ("diamond", "Diamond"),
                    ("gold", "Gold"),
                    ("silver", "Silver"),
                    ("bronze", "Bronze"),
                ],
                default="bronze",
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="BadgeProgress",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("acquired", models.DateTimeField(default=None, null=True)),
                ("progress", models.IntegerField(default=0)),
                (
                    "badge",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="badge_progresses",
                        to="skole.badge",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="badge_progresses",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "unique_together": {("badge", "user")},
            },
        ),
        migrations.AddField(
            model_name="user",
            name="selected_badge_progress",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="users",
                to="skole.badgeprogress",
            ),
        ),
    ]
