# Generated by Django 3.1.7 on 2021-03-21 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("skole", "0023_badge_activity"),
    ]

    operations = [
        migrations.AddField(
            model_name="badge",
            name="made_available",
            field=models.BooleanField(default=False),
        ),
    ]
