# Generated by Django 3.1.5 on 2021-03-22 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('skole', '0024_badge_made_available'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EmailSubscription',
        ),
        migrations.RemoveField(
            model_name='user',
            name='blog_post_email_permission',
        ),
        migrations.RemoveField(
            model_name='user',
            name='product_update_email_permission',
        ),
        migrations.DeleteModel(
            name='MarketingEmail',
        ),
        migrations.DeleteModel(
            name='MarketingEmailSender',
        ),
    ]
