# Generated by Django 3.1.7 on 2021-03-23 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("skole", "0024_badge_made_available"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="comment_reply_email_permission",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="user",
            name="course_comment_email_permission",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="user",
            name="new_badge_email_permission",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="user",
            name="resource_comment_email_permission",
            field=models.BooleanField(default=False),
        ),
    ]
