# Generated by Django 3.1.7 on 2021-03-26 14:09

from django.db import migrations, models

import skole.utils.validators


class Migration(migrations.Migration):

    dependencies = [
        ("skole", "0032_move_school_comments_to_threads"),
    ]

    operations = [
        migrations.RenameField(
            model_name="comment",
            old_name="attachment",
            new_name="image",
        ),
        migrations.AddField(
            model_name="comment",
            name="file",
            field=models.FileField(
                blank=True,
                max_length=500,
                upload_to="uploads/resources",
                validators=[
                    skole.utils.validators.ValidateFileSizeAndType(
                        10, [("application/pdf", "PDF")]
                    )
                ],
            ),
        ),
    ]
