# Generated by Django 3.1.7 on 2021-03-26 15:04
# Manually edited to add the `forwards_func`.
from __future__ import annotations

from django.apps.registry import Apps
from django.db import migrations
from django.db.backends.base.schema import BaseDatabaseSchemaEditor


def forwards_func(apps: Apps, schema_editor: BaseDatabaseSchemaEditor) -> None:
    """Delete all Activities that belong to Resource comments."""
    Activity = apps.get_model("skole", "Activity")
    Activity.objects.filter(activity_type__identifier="resource_comment").delete()


class Migration(migrations.Migration):

    dependencies = [
        ("skole", "0034_resources_to_comments"),
    ]

    operations = [
        migrations.RunPython(
            code=forwards_func, reverse_code=migrations.RunPython.noop
        ),
    ]
