# Generated by Django 3.1.7 on 2021-03-27 09:17

from __future__ import annotations

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("skole", "0038_massive_model_delete"),
    ]

    operations = [
        migrations.AddField(
            model_name="comment",
            name="is_anonymous",
            field=models.BooleanField(default=False),
        ),
    ]
