# Generated by Django 3.1.7 on 2021-04-01 11:38

from __future__ import annotations

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("skole", "0042_recompute_user_scores"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="backup_email",
            field=models.EmailField(blank=True, max_length=254),
        ),
    ]
