# Generated by Django 3.1.7 on 2021-04-04 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("skole", "0044_big_auto_field_pk"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="verified_backup_email",
            field=models.BooleanField(default=True),
        ),
    ]
