# Generated by Django 3.2 on 2021-04-08 21:44

from __future__ import annotations

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("skole", "0048_issue_invite_codes_to_existing_users"),
    ]

    operations = [
        migrations.AlterField(
            model_name="invitecode",
            name="user",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="invite_code",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
