# Generated by Django 3.2 on 2021-04-11 11:33

from __future__ import annotations

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("skole", "0049_one_to_one_invite_code"),
    ]

    operations = [
        migrations.AlterField(
            model_name="invitecode",
            name="user",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="invite_code",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
