# Generated by Django 3.2 on 2021-04-12 15:46
# Manually edited to take the default value from settings.
from __future__ import annotations

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("skole", "0054_fix_sequences"),
    ]

    operations = [
        migrations.AddField(
            model_name="invitecode",
            name="initial_usages",
            field=models.PositiveIntegerField(default=2),
        ),
    ]
