# Generated by Django 3.2 on 2021-04-23 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("skole", "0059_recalculate_thread_comment_scores"),
    ]

    operations = [
        migrations.AddField(
            model_name="comment",
            name="file_thumbnail",
            field=models.ImageField(blank=True, upload_to="generated/thumbnails"),
        ),
    ]
