# Generated by Django 3.2.2 on 2021-08-11 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("skole", "0060_comment_file_thumbnail"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="used_invite_code",
        ),
        migrations.DeleteModel(
            name="InviteCode",
        ),
    ]
