# Generated by Django 2.2.6 on 2019-10-12 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='school_type',
            field=models.CharField(choices=[('UNIVERSITY', 'University'), ('UNIVERSITY_OF_APPLIED_SCIENCES', 'University of Applied Sciences'), ('HIGH_SCHOOL', 'High School')], max_length=30),
        ),
    ]
