# Generated by Django 2.2.6 on 2019-10-26 10:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('core', '0004_auto_20191020_1500'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.ImageField(null=True, upload_to='uploads/avatars'),
        ),
    ]
