# Generated by Django 2.2.7 on 2019-11-07 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20191102_1311'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='school',
        ),
        migrations.AddField(
            model_name='subject',
            name='schools',
            field=models.ManyToManyField(related_name='schools', to='core.School'),
        ),
    ]
