# Generated by Django 2.2.7 on 2019-11-07 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20191107_1506'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='schools',
            field=models.ManyToManyField(related_name='subjects', to='core.School'),
        ),
    ]
