UNIVERSITY = "UNIVERSITY"
UNIVERSITY_OF_APPLIED_SCIENCES = "UNIVERSITY_OF_APPLIED_SCIENCES"
HIGH_SCHOOL = "HIGH_SCHOOL"

SCHOOL_TYPES = (
    (UNIVERSITY, "University"),
    (UNIVERSITY_OF_APPLIED_SCIENCES, "University of Applied Sciences"),
    (HIGH_SCHOOL, "High School"),
)
